In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("Student_Data.csv")

In [2]:
#To get information like no. of rows , columns, data types,Missing Values.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  20 non-null     object
 1   Name        20 non-null     object
 2   Department  20 non-null     object
 3   Age         20 non-null     int64
 4   Marks       20 non-null     int64
 5   Attendance  20 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.1+ KB

In [3]:
#prints out specified columns
df[["Name","Attendance"]]

         Name  Attendance
0       Advik         100
1   Abhijeeth          96
2     Sherwin          93
3        Diya          77
4      Pranav          89
5      Ashwin          76
6       Anish          99
7   Yashwanth          94
8     Chinmay          85
9      Adarsh          79
10     Vishnu          92
11       Jude          90
12      Jacob          81
13        Max          87
14      Jason          99
15    Charles         100
16      Lewis          71
17     Thomas          84
18      Shawn          96
19       Jack          99

In [4]:
#filters out data based on condition for specified column
df[df["Marks"]>80]

   Student_ID       Name Department  Age  Marks  Attendance
0       25B01      Advik        CSE   19     98         100
1       25B02  Abhijeeth        CSE   18     92          96
2       25B03    Sherwin       MECH   19     88          93
3       25B04       Diya        CSE   20     94          77
5       25B06     Ashwin        ECE   22     90          76
6       25B07      Anish       MECH   20     96          99
7       25B08  Yashwanth     DESIGN   19     88          94
9       25B10     Adarsh     DESIGN   18     97          79
11      25B12       Jude       AIML   19     83          90
12      25B13      Jacob       AIML   23     90          81
15      25B16    Charles        CSE   21     90         100
16      25B17      Lewis        CSE   18     85          71
17      25B18     Thomas        CSE   20     91          84
18      25B19      Shawn       MECH   20     88          96

In [5]:
#sorts based on marks
df.sort_values(by="Marks")

   Student_ID       Name Department  Age  Marks  Attendance
10      25B11     Vishnu        ECE   18     64          92
19      25B20       Jack       AIML   19     66          99
14      25B15      Jason        ECE   19     68          99
4       25B05     Pranav        ECE   19     72          89
8       25B09    Chinmay       AIML   23     75          85
13      25B14        Max        CSE   22     79          87
11      25B12       Jude       AIML   19     83          90
16      25B17      Lewis        CSE   18     85          71
7       25B08  Yashwanth     DESIGN   19     88          94
18      25B19      Shawn       MECH   20     88          96
2       25B03    Sherwin       MECH   19     88          93
5       25B06     Ashwin        ECE   22     90          76
15      25B16    Charles        CSE   21     90         100
12      25B13      Jacob       AIML   23     90          81
17      25B18     Thomas        CSE   20     91          84
1       25B02  Abhijeeth        CSE   18     92          96
3       25B04       Diya        CSE   20     94          77
6       25B07      Anish       MECH   20     96          99
9       25B10     Adarsh     DESIGN   18     97          79
0       25B01      Advik        CSE   19     98         100

In [11]:
#descending order sorting
df.sort_values(by="Marks",ascending=False)

   Student_ID       Name Department  Age  Marks  Attendance
0       25B01      Advik        CSE   19     98         100
9       25B10     Adarsh     DESIGN   18     97          79
6       25B07      Anish       MECH   20     96          99
3       25B04       Diya        CSE   20     94          77
1       25B02  Abhijeeth        CSE   18     92          96
17      25B18     Thomas        CSE   20     91          84
12      25B13      Jacob       AIML   23     90          81
5       25B06     Ashwin        ECE   22     90          76
15      25B16    Charles        CSE   21     90         100
2       25B03    Sherwin       MECH   19     88          93
18      25B19      Shawn       MECH   20     88          96
7       25B08  Yashwanth     DESIGN   19     88          94
16      25B17      Lewis        CSE   18     85          71
11      25B12       Jude       AIML   19     83          90
13      25B14        Max        CSE   22     79          87
8       25B09    Chinmay       AIML   23     75          85
4       25B05     Pranav        ECE   19     72          89
14      25B15      Jason        ECE   19     68          99
19      25B20       Jack       AIML   19     66          99
10      25B11     Vishnu        ECE   18     64          92

In [12]:
#print the mean for the chosen column
print(df["Marks"].mean())

84.7

In [17]:
#prints entire row with the condition of marks equal to max marks
df[df["Marks"]==df["Marks"].max()]

  Student_ID   Name Department  Age  Marks  Attendance
0      25B01  Advik        CSE   19     98         100

In [18]:
#prints sum of the entire column
print(df["Marks"].sum())

1694

In [19]:
#Number of unique values in the dept column
df["Department"].nunique()

5

In [23]:
#merging two datasets(it findss rows with same value for a column and combines the information from those rows into one row)
df2 = pd.DataFrame({
    'Student_ID': ['25B01','25B02','25B08','25B09','25B15','25B16','25B20'],
    'Project_Progress(%)': [90,50,60,33,75,45,10]
})

pd.merge(df, df2, on="Student_ID")
#Finally only prints the ones it merged

,Student_ID,Name,Department,Age,Marks,Attendance,Project_Progress(%)
0,25B01,Advik,CSE,19,98,100,90
1,25B02,Abhijeeth,CSE,18,92,96,50
2,25B08,Yashwanth,DESIGN,19,88,94,60
3,25B09,Chinmay,AIML,23,75,85,33
4,25B15,Jason,ECE,19,68,99,75
5,25B16,Charles,CSE,21,90,100,45
6,25B20,Jack,AIML,19,66,99,10

In [26]:
df3=pd.DataFrame({
    'Student_ID':('25B21','25B22','25B23'),
    'Name':('James','Richard','Clarkson'),
    'Department':('DESIGN','MECH','CSE'),
    'Marks':('92','88','94'),
    'Attendance':('75','88','99')
})
pd.concat([df,df3])

   Student_ID       Name Department   Age Marks Attendance
0       25B01      Advik        CSE  19.0    98        100
1       25B02  Abhijeeth        CSE  18.0    92         96
2       25B03    Sherwin       MECH  19.0    88         93
3       25B04       Diya        CSE  20.0    94         77
4       25B05     Pranav        ECE  19.0    72         89
5       25B06     Ashwin        ECE  22.0    90         76
6       25B07      Anish       MECH  20.0    96         99
7       25B08  Yashwanth     DESIGN  19.0    88         94
8       25B09    Chinmay       AIML  23.0    75         85
9       25B10     Adarsh     DESIGN  18.0    97         79
10      25B11     Vishnu        ECE  18.0    64         92
11      25B12       Jude       AIML  19.0    83         90
12      25B13      Jacob       AIML  23.0    90         81
13      25B14        Max        CSE  22.0    79         87
14      25B15      Jason        ECE  19.0    68         99
15      25B16    Charles        CSE  21.0    90        100
16      25B17      Lewis        CSE  18.0    85         71
17      25B18     Thomas        CSE  20.0    91         84
18      25B19      Shawn       MECH  20.0    88         96
19      25B20       Jack       AIML  19.0    66         99
0       25B21      James     DESIGN   NaN    92         75
1       25B22    Richard       MECH   NaN    88         88
2       25B23   Clarkson        CSE   NaN    94         99