In [ ]:
import pandas as pd
import numpy as np

df1SE =  pd.DataFrame({ 'StudentID': [8, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'ScoreSE' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2SE =  pd.DataFrame({'StudentID': [2, 4, 3, 8, 10, 12, 99, 16, 18, 20, 22, 24, 26, 28, 30],
                       'ScoreSE': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

df1ML =  pd.DataFrame({ 'StudentID': [9, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'ScoreML' : [79, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
df2ML =  pd.DataFrame({'StudentID': [29, 4, 6, 8, 10, 12, 14, 16, 18, 20],
                       'ScoreML': [67, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [ ]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = pd.concat([dfML, dfSE], axis=1)
df

    StudentID  ScoreML  StudentID  ScoreSE
0         9.0     79.0          8       22
1         3.0     49.0         11       66
2         5.0     55.0         13       31
3         7.0     77.0         15       51
4         9.0     52.0         17       71
5        11.0     86.0         19       91
6        13.0     41.0         21       56
7        15.0     77.0         23       32
8        17.0     73.0         25       52
9        19.0     51.0         27       73
10       21.0     86.0         29       92
11       23.0     82.0          2       98
12       25.0     92.0          4       93
13       27.0     23.0          3       44
14       29.0     49.0          8       77
15       29.0     67.0         10       69
16        4.0     44.0         12       56
17        6.0     78.0         99       31
18        8.0     97.0         16       53
19       10.0     87.0         18       78
20       12.0     89.0         20       93
21       14.0     39.0         22       56
22       16.0     43.0         24       77
23       18.0     88.0         26       33
24       20.0     78.0         28       56
25        NaN      NaN         30       27

In [ ]:
df = dfSE.merge(dfML, how='inner')
df

    StudentID  ScoreSE  ScoreML
0           8       22       97
1          11       66       86
2          13       31       41
3          15       51       77
4          17       71       73
5          19       91       51
6          21       56       86
7          23       32       82
8          25       52       92
9          27       73       23
10         29       92       49
11         29       92       67
12          4       93       44
13          3       44       49
14          8       77       97
15         10       69       87
16         12       56       89
17         16       53       43
18         18       78       88
19         20       93       78

In [ ]:
df = dfSE.merge(dfML, how='outer')
df

    StudentID  ScoreSE  ScoreML
0           2     98.0      NaN
1           3     44.0     49.0
2           4     93.0     44.0
3           5      NaN     55.0
4           6      NaN     78.0
5           7      NaN     77.0
6           8     22.0     97.0
7           8     77.0     97.0
8           9      NaN     79.0
9           9      NaN     52.0
10         10     69.0     87.0
11         11     66.0     86.0
12         12     56.0     89.0
13         13     31.0     41.0
14         14      NaN     39.0
15         15     51.0     77.0
16         16     53.0     43.0
17         17     71.0     73.0
18         18     78.0     88.0
19         19     91.0     51.0
20         20     93.0     78.0
21         21     56.0     86.0
22         22     56.0      NaN
23         23     32.0     82.0
24         24     77.0      NaN
25         25     52.0     92.0
26         26     33.0      NaN
27         27     73.0     23.0
28         28     56.0      NaN
29         29     92.0     49.0
30         29     92.0     67.0
31         30     27.0      NaN
32         99     31.0      NaN

In [ ]:
df = dfSE.merge(dfML, how='left')
df

    StudentID  ScoreSE  ScoreML
0           8       22     97.0
1          11       66     86.0
2          13       31     41.0
3          15       51     77.0
4          17       71     73.0
5          19       91     51.0
6          21       56     86.0
7          23       32     82.0
8          25       52     92.0
9          27       73     23.0
10         29       92     49.0
11         29       92     67.0
12          2       98      NaN
13          4       93     44.0
14          3       44     49.0
15          8       77     97.0
16         10       69     87.0
17         12       56     89.0
18         99       31      NaN
19         16       53     43.0
20         18       78     88.0
21         20       93     78.0
22         22       56      NaN
23         24       77      NaN
24         26       33      NaN
25         28       56      NaN
26         30       27      NaN

In [ ]:
df = dfSE.merge(dfML, how='right')
df

    StudentID  ScoreSE  ScoreML
0           9      NaN       79
1           3     44.0       49
2           5      NaN       55
3           7      NaN       77
4           9      NaN       52
5          11     66.0       86
6          13     31.0       41
7          15     51.0       77
8          17     71.0       73
9          19     91.0       51
10         21     56.0       86
11         23     32.0       82
12         25     52.0       92
13         27     73.0       23
14         29     92.0       49
15         29     92.0       67
16          4     93.0       44
17          6      NaN       78
18          8     22.0       97
19          8     77.0       97
20         10     69.0       87
21         12     56.0       89
22         14      NaN       39
23         16     53.0       43
24         18     78.0       88
25         20     93.0       78

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/sales.csv')
df.head(10)

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004,2474,136,True
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006,4081,195,False
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999,2460,36,False
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004,1831,664,True

In [ ]:
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']
df.head(10)

df['Company'].value_counts()

df.describe()

,Account,Order,Year,Quantity,UnitPrice,TotalPrice
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04
mean,1.234568e+08,99989.562900,1994.619800,4985.447300,355.866600,1.773301e+06
std,5.741156e+00,5.905551,14.432771,2868.949686,201.378478,1.540646e+06
min,1.234568e+08,99980.000000,1970.000000,0.000000,10.000000,0.000000e+00
25%,1.234568e+08,99985.000000,1982.000000,2505.750000,181.000000,5.003370e+05
50%,1.234568e+08,99990.000000,1995.000000,4994.000000,356.000000,1.335698e+06
75%,1.234568e+08,99995.000000,2007.000000,7451.500000,531.000000,2.711653e+06
max,1.234568e+08,99999.000000,2019.000000,9999.000000,700.000000,6.841580e+06

In [ ]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1
stacked = dframe1.stack()
stacked
stacked.unstack()

series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN

In [ ]:
frame2

Number1  zeros       0
         ones      111
         twos      222
         threes    333
Number2  fours     444
         fives     555
         sixs      666
dtype: int64